services:
  - type: web
    name: truck-loading-simulator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
